---
- name: Application={{ package }} will be in state {{ state }}
  hosts: windows
  gather_facts: false
  tasks:
    - name: add/remove package
      win_chocolatey:
        name: "{{ package }}"
        state: "{{ state }}"