---
- name: Installs Windows EXE
  hosts: windows
  tasks:
    - name: Install 7zip with win_package
      win_package:
        path: C:\Program Files\7-Zip\7z.exe
        product_id: 7-Zip
        arguments: /S
        state: absent