---
- name: Installs Windows EXE
  hosts: windows
  tasks:
    - name: Install 7zip with win_package
      win_package:
        path: C:\apps\7z1900-x64.exe
        creates_path: C:\Program Files\7-Zip\7z.exe
        creates_version: 19.00
        state: present