---
- name: Modify application on RHEL and Ubuntu
  hosts: test_rhel,ubuntu
  tasks:
    - name: Modify application on RHEL
      yum:
        name: "{{ package }}"
        state: "{{ state }}"
      when: ansible_distribution == 'RedHat'

    - name: Modify application on Ubuntu
      apt:
        name: "{{ package }}"
        state: "{{ state }}"
      when: ansible_distribution == 'Ubuntu'