---
- name: Update All RHEL and Ubuntu
  hosts: all
  tasks:
    - name: Update RHEL
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Update Ubuntu
      apt:
        name: "*"
        state: latest
      when: ansible_distribution == 'Ubuntu'